version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx #容器名称
    ports:
      - 80:80
    volumes:
      - /mnt/e/opt/nginx.conf:/etc/nginx/nginx.conf
    deploy:
     resources:
        limits:
           cpus: '2'
           memory: 10M
        reservations:
           cpus: '0.5'
           memory: 5M
 

