version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    networks:
      - net-es
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
 
  elastichd:
    image: containerize/elastichd:latest
    container_name: elasticsearch-hd
    networks:
      - net-es
    ports:
      - "9800:9800"
    depends_on:
      - "elasticsearch"
      # 链接到其它容器，并启别名elasticsearch
    links:
      - "elasticsearch:elasticsearch"
 
#这里要注意，es和eshd要在相同网络才能被links
networks:
  net-es:
    external: false